'''
This file implements all of the functionality in order to manage stock price alerts through interaction with the PostgreSQL database.
'''

import psycopg as postgres

'''
Go to the following link for information about the PostgreSQL connection string, which is the single argument that's used in the connect() calls below:
https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
'''

def get(id):
  '''
  Get stock price alert by id.
  '''

def create(id, ticker, price, direction, one_time, expiration_date):
  '''
  Create a new stock price alert.
  Parameters:
    - id: Generally unnecessary because it is autogenerated in the table via SERIAL. Parameter is left in the function definition in case we wish to overwrite the auto-generated id.
  '''
  # Connect to an existing database
  with postgres.connect('host=localhost port=5432 dbname=portfolio_insights') as connection:
   # Open a cursor to perform database operations
   with connection.cursor() as database:
      database.execute('''
                       INSERT INTO alerts (ticker, price, direction, one_time, creation_date, expiration_date)
                       VALUES ('SPXL', 225.00, 'below', true, NOW(), NOW() + INTERVAL '7 days');
                       ''')

def delete(id):
  '''
  Delete a stock price alert by id.
  '''

def update(id):
  '''
  Update a stock price alert by id.
  '''